# Generated by Django 4.2.2 on 2023-08-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ent_seq', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KEle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keb', models.CharField(max_length=64)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
                ('ke_inf', models.ManyToManyField(related_name='ke_inf', to='dictionary.entity')),
                ('ke_pri', models.ManyToManyField(related_name='ke_pri', to='dictionary.entity')),
            ],
        ),
        migrations.CreateModel(
            name='REle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reb', models.CharField(max_length=64)),
                ('re_nokanji', models.BooleanField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
                ('re_inf', models.ManyToManyField(related_name='re_inf', to='dictionary.entity')),
                ('re_pri', models.ManyToManyField(related_name='re_pri', to='dictionary.entity')),
                ('re_restr', models.ManyToManyField(to='dictionary.kele')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_inf', models.CharField(max_length=64, null=True)),
                ('dial', models.ManyToManyField(related_name='dial', to='dictionary.entity')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry')),
                ('field', models.ManyToManyField(related_name='field', to='dictionary.entity')),
                ('misc', models.ManyToManyField(related_name='misc', to='dictionary.entity')),
                ('pos', models.ManyToManyField(related_name='pos', to='dictionary.entity')),
                ('stagk', models.ManyToManyField(to='dictionary.kele')),
                ('stagr', models.ManyToManyField(to='dictionary.rele')),
            ],
        ),
        migrations.CreateModel(
            name='LSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='eng', max_length=8)),
                ('ls_wasei', models.BooleanField(default=False)),
                ('ls_type', models.CharField(default='full', max_length=8, null=True)),
                ('value', models.CharField(max_length=64, null=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sense')),
            ],
        ),
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='eng', max_length=8)),
                ('g_type', models.CharField(max_length=8, null=True)),
                ('g_gend', models.CharField(max_length=8, null=True)),
                ('content', models.CharField(max_length=64, null=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sense')),
            ],
        ),
    ]
